# Data Wrangling I
Perform the following operations using Python on any open source dataset (e.g., data.csv)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g. https://www.kaggle.com). Provide a clear
description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas data frame.
4. Data Preprocessing: check for missing values in the data using pandas insult(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables
etc. Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking
the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the
data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
In addition to the codes and outputs, explain every operation that y

In [30]:
# Upgrade pip and setuptools
!pip install --upgrade pip
!pip install --upgrade setuptools

# Install pandas using pre-built binaries
!pip install pandas
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\programdata\anaconda3\lib\site-packages (23.1.2)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
                                              0.0/2.1 MB ? eta -:--:--
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     -                                        0.1/2.1 MB 261.7 kB/s eta 0:00:08
     --                                       0.2/2.1 MB 176.3 kB/s eta 0:00:12
     --                                       0.2/2.1 MB 176.3 kB/s eta 0:00:12
     ---                                      0.2/2.1 MB 183.9 kB/s eta 0:00:11
     ---                                      0.2/2.1 MB 183.9 kB/s eta 0:00:11
     ---                                      0.2/2.1 MB 183.9 kB/s eta 0:00:11
     ---                                      0.2/2.1 MB 183.9 kB/s eta 0:00:11
     ---                                      0.2/2.1 MB 183.9 kB/s eta 0:00:11
     -----                                    0.3/2.1 MB 233.3 kB/s eta 0:00:08
     -----                                    0.3/2.1 MB 233.3 kB/s eta 0:00:08
     -----                                    0.3/2.1 MB 233.3 kB/s eta 0:00:08
     -----                                    0.3/2.1 MB 233.3 kB/s eta 0:00:08
     -----                                    0.3/2.1 MB 233.3 kB/s eta 0:00:08
     -----                                    0.3/2.1 MB 198.8 kB/s eta 0:00:10
     -------                                  0.4/2.1 MB 266.4 kB/s eta 0:00:07
     -------                                  0.4/2.1 MB 262.0 kB/s eta 0:00:07
     --------                                 0.4/2.1 MB 280.9 kB/s eta 0:00:06
     ---------                                0.5/2.1 MB 298.5 kB/s eta 0:00:06
     ----------                               0.5/2.1 MB 321.4 kB/s eta 0:00:05
     -----------                              0.6/2.1 MB 364.8 kB/s eta 0:00:05
     -------------                            0.7/2.1 MB 399.1 kB/s eta 0:00:04
     --------------                           0.8/2.1 MB 438.9 kB/s eta 0:00:04
     ----------------                         0.8/2.1 MB 467.3 kB/s eta 0:00:03
     -----------------                        0.9/2.1 MB 495.5 kB/s eta 0:00:03
     -------------------                      1.0/2.1 MB 531.9 kB/s eta 0:00:03
     --------------------                     1.1/2.1 MB 545.3 kB/s eta 0:00:02
     ----------------------                   1.2/2.1 MB 583.7 kB/s eta 0:00:02
     ----------------------                   1.2/2.1 MB 599.0 kB/s eta 0:00:02
     -------------------------                1.4/2.1 MB 645.5 kB/s eta 0:00:02
     --------------------------               1.4/2.1 MB 650.5 kB/s eta 0:00:02
     ----------------------------             1.5/2.1 MB 688.0 kB/s eta 0:00:01
     ------------------------------           1.6/2.1 MB 710.7 kB/s eta 0:00:01
     ------------------------------           1.6/2.1 MB 710.7 kB/s eta 0:00:01
     ------------------------------           1.6/2.1 MB 710.7 kB/s eta 0:00:01
     --------------------------------         1.7/2.1 MB 715.7 kB/s eta 0:00:01
     ---------------------------------        1.8/2.1 MB 737.3 kB/s eta 0:00:01
     ---------------------------------        1.8/2.1 MB 718.0 kB/s eta 0:00:01
     -----------------------------------      1.9/2.1 MB 740.7 kB/s eta 0:00:01
     -------------------------------------    2.0/2.1 MB 759.1 kB/s eta 0:00:01
     ---------------------------------------  2.1/2.1 MB 793.5 kB/s eta 0:00:01
     ---------------------------------------- 2.1/2.1 MB 794.8 kB/s eta 0:00:00

ERROR: To modify pip, please run the following command:
C:\ProgramData\anaconda3\python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (67.8.0)
Collecting setuptools
  Downloading setuptools-69.0.3-py3-none-any.whl (819 kB)
                                              0.0/819.5 kB ? eta -:--:--
     -                                       30.7/819.5 kB 1.4 MB/s eta 0:00:01
     ---                                   81.9/819.5 kB 919.0 kB/s eta 0:00:01
     ----                                 112.6/819.5 kB 819.2 kB/s eta 0:00:01
     ----------                             225.3/819.5 kB 1.3 MB/s eta 0:00:01
     ----------------                       348.2/819.5 kB 1.4 MB/s eta 0:00:01
     ----------------------                 491.5/819.5 kB 1.8 MB/s eta 0:00:01
     --------------------------------       696.3/819.5 kB 2.1 MB/s eta 0:00:01
     -------------------------------------- 819.5/819.5 kB 2.3 MB/s eta 0:00:00
Installing collected packages: setuptools
Successfully installed setuptools-69.0.3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.29.0 which is incompatible.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas) (1.26.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\user\appdata\roaming\python\python311\site-packages (1.26.2)

In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("https://raw.githubusercontent.com/manish0222/TE_SEM_6/main/ds_lab/ASGN1/melb_data_1.csv")
# df = pd.read_csv("melb_data_1.csv")
df  # check if its imported properly

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [2]:
df.describe()   # count , mean , std , max and min

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [3]:
columns_to_describe = ['Car', 'BuildingArea','CouncilArea', 'YearBuilt' ]
df[columns_to_describe].describe()  
#Council area is object datatype and hence it cannot be determined

                Car  BuildingArea    YearBuilt
count  13518.000000   7130.000000  8205.000000
mean       1.610075    151.967650  1964.684217
std        0.962634    541.014538    37.273762
min        0.000000      0.000000  1196.000000
25%        1.000000     93.000000  1940.000000
50%        2.000000    126.000000  1970.000000
75%        2.000000    174.000000  1999.000000
max       10.000000  44515.000000  2018.000000

In [4]:
df.head() # describes first 5 entries
#df.head(8) # first 8 entries from top

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [32]:
# tell if any value is null or not
print("The shape is ",df.shape)
df.isna().sum()

The shape is  (13580, 21)

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

### Filling Null values and 2 methods

In [33]:
columns_to_fill = ['Car', 'BuildingArea', 'YearBuilt' ]
df[columns_to_fill] = df[columns_to_fill].fillna(df[columns_to_fill].mean())
print("The shape is ",df.shape)
df

The shape is  (13580, 21)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,151.96765,1981.000000,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.00000,1995.000000,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,151.96765,1997.000000,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.00000,1920.000000,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.00000,1920.000000,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [34]:
print("The shape is ",df.shape)
df.isna().sum()
df=df.ffill()  #forward fill the null values by previous non null values
df=df.bfill()  # backward fill in background
df

The shape is  (13580, 21)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,151.96765,1981.000000,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.00000,1995.000000,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,151.96765,1997.000000,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.00000,1920.000000,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.00000,1920.000000,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [8]:
df.isna().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [9]:
# shape is no of rows and columns
df.shape

(13580, 21)

In [10]:
# show datatypes of each row
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [11]:
#  to change a data type
df=df.astype({'YearBuilt':int})
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt          int32
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [12]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [13]:
df['Rooms'].unique() # unique values present in column

array([ 2,  3,  4,  1,  6,  5,  8,  7, 10], dtype=int64)

In [14]:
# Calculate the square root in-place
# df['column_name_sqrt'] = np.sqrt(df['column_name'])   Done for different column 
df['Landsize'] = np.sqrt(df['Landsize'])

#### Indexing and slicing in array

In [15]:
# print("\nElement at (1, 2):", arr_2d[1, 2])
# print("First row:", arr_2d[0, :])
# print("Last column:", arr_2d[:, -1])
df['CouncilArea'].unique().size

33

# Categorical Replacement

In [16]:
#Replace Method  
#                                    NOT used Dummy Method
df['Rooms'].replace([1,2,3,4,5,6,7,8,10],
                    ['1BHK','2BHK','3BHK','4BHK','5BHK','6BHK','7BHK','8BHK','10BHK'],inplace=True)
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,14.212670,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,12.489996,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,11.575837,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,9.695360,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,10.954451,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,25.534291,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,18.248288,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,20.880613,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,29.427878,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,19.026298,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [17]:
!pip install category_encoders

import category_encoders as ce

# Assume df is your DataFrame with 'Rooms' column modified
# Display the original DataFrame
print("Original DataFrame:")
df

Defaulting to user installation because normal site-packages is not writeable
Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
                                              0.0/81.9 kB ? eta -:--:--
     ---------------                          30.7/81.9 kB ? eta -:--:--
     ---------------                          30.7/81.9 kB ? eta -:--:--
     ---------------                          30.7/81.9 kB ? eta -:--:--
     ---------------                          30.7/81.9 kB ? eta -:--:--
     -------------------------------------- 81.9/81.9 kB 328.5 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from category_encoders) (1.26.2)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\programdata\anaconda3\lib\site-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from category_encoders) (1.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from category_encoders) (0.13.5)
Requirement already satisfied: pandas>=1.0.5 in c:\programdata\anaconda3\lib\site-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in c:\programdata\anaconda3\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2022.7)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\programdata\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.0)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.3
Original DataFrame:

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,14.212670,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,12.489996,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,11.575837,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,9.695360,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,10.954451,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,25.534291,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,18.248288,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,20.880613,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,29.427878,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,19.026298,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0

In [21]:
# 1. Label Encoding for 'Rooms'
label_encoder_rooms = LabelEncoder()
df['Rooms_LabelEncoded'] = label_encoder_rooms.fit_transform(df['Rooms'])
new_arr=['Rooms_LabelEncoded','Rooms']
# Display the DataFrame after Label Encoding for 'Rooms'
print("\nDataFrame after Label Encoding for 'Rooms':")
df[new_arr]

DataFrame after Label Encoding for 'Rooms':

       Rooms_LabelEncoded Rooms
0                       2  2BHK
1                       2  2BHK
2                       3  3BHK
3                       3  3BHK
4                       4  4BHK
...                   ...   ...
13575                   4  4BHK
13576                   3  3BHK
13577                   3  3BHK
13578                   4  4BHK
13579                   4  4BHK

[13580 rows x 2 columns]

In [25]:
# 2. One-Hot Encoding for 'Rooms'
df_one_hot_rooms = pd.get_dummies(df, columns=['Rooms'], prefix=['Rooms'])

# Display the DataFrame after One-Hot Encoding for 'Rooms' 
# number of colums increases now of categories = number of new columns
print("\nDataFrame after One-Hot Encoding for 'Rooms':")
df_one_hot_rooms

DataFrame after One-Hot Encoding for 'Rooms':

,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,...,Rooms_LabelEncoded,Rooms_10BHK,Rooms_1BHK,Rooms_2BHK,Rooms_3BHK,Rooms_4BHK,Rooms_5BHK,Rooms_6BHK,Rooms_7BHK,Rooms_8BHK
0,Abbotsford,85 Turner St,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,...,2,0,0,1,0,0,0,0,0,0
1,Abbotsford,25 Bloomburg St,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,...,2,0,0,1,0,0,0,0,0,0
2,Abbotsford,5 Charles St,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,...,3,0,0,0,1,0,0,0,0,0
3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,...,3,0,0,0,1,0,0,0,0,0
4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,...,4,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,4.0,...,4,0,0,0,0,1,0,0,0,0
13576,Williamstown,77 Merrett Dr,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,3.0,...,3,0,0,0,1,0,0,0,0,0
13577,Williamstown,83 Power St,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,3.0,...,3,0,0,0,1,0,0,0,0,0
13578,Williamstown,96 Verdon St,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,4.0,...,4,0,0,0,0,1,0,0,0,0
13579,Yarraville,6 Agnes St,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,4.0,...,4,0,0,0,0,1,0,0,0,0

In [28]:
# 3. Ordinal Encoding for 'Rooms'
ordinal_mapping_rooms = {'1BHK': 0, '2BHK': 1, '3BHK': 2, '4BHK': 3, '5BHK': 4, '6BHK': 5, '7BHK': 6, '8BHK': 7, '10BHK': 8}
df['Rooms_OrdinalEncoded'] = df['Rooms'].map(ordinal_mapping_rooms)
new_arr.append('Rooms_OrdinalEncoded')
# Display the DataFrame after Ordinal Encoding for 'Rooms'
print("\nDataFrame after Ordinal Encoding for 'Rooms':")
df[new_arr].head(25)

DataFrame after Ordinal Encoding for 'Rooms':

,Rooms_LabelEncoded,Rooms,Rooms_OrdinalEncoded,Rooms_OrdinalEncoded,Rooms_OrdinalEncoded
0,2,2BHK,1,1,1
1,2,2BHK,1,1,1
2,3,3BHK,2,2,2
3,3,3BHK,2,2,2
4,4,4BHK,3,3,3
5,2,2BHK,1,1,1
6,3,3BHK,2,2,2
7,2,2BHK,1,1,1
8,1,1BHK,0,0,0
9,2,2BHK,1,1,1
10,2,2BHK,1,1,1
11,3,3BHK,2,2,2
12,2,2BHK,1,1,1
13,2,2BHK,1,1,1
14,1,1BHK,0,0,0
15,2,2BHK,1,1,1
16,3,3BHK,2,2,2
17,3,3BHK,2,2,2
18,3,3BHK,2,2,2
19,2,2BHK,1,1,1
20,4,4BHK,3,3,3
21,3,3BHK,2,2,2
22,3,3BHK,2,2,2
23,2,2BHK,1,1,1
24,2,2BHK,1,1,1

In [29]:
# 4. Binary Encoding for 'Rooms'
binary_encoder_rooms = ce.BinaryEncoder(cols=['Rooms'])
df_binary_rooms = binary_encoder_rooms.fit_transform(df)

# Display the DataFrame after Binary Encoding for 'Rooms'
print("\nDataFrame after Binary Encoding for 'Rooms':")
df_binary_rooms

DataFrame after Binary Encoding for 'Rooms':

,Suburb,Address,Rooms_0,Rooms_1,Rooms_2,Rooms_3,Type,Price,Method,SellerG,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_LabelEncoded,Rooms_OrdinalEncoded
0,Abbotsford,85 Turner St,0,0,0,1,h,1480000.0,S,Biggin,...,14.212670,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,1
1,Abbotsford,25 Bloomburg St,0,0,0,1,h,1035000.0,S,Biggin,...,12.489996,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,1
2,Abbotsford,5 Charles St,0,0,1,0,h,1465000.0,SP,Biggin,...,11.575837,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,2
3,Abbotsford,40 Federation La,0,0,1,0,h,850000.0,PI,Biggin,...,9.695360,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,2
4,Abbotsford,55a Park St,0,0,1,1,h,1600000.0,VB,Nelson,...,10.954451,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,0,0,1,1,h,1245000.0,S,Barry,...,25.534291,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,3
13576,Williamstown,77 Merrett Dr,0,0,1,0,h,1031000.0,SP,Williams,...,18.248288,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,2
13577,Williamstown,83 Power St,0,0,1,0,h,1170000.0,S,Raine,...,20.880613,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,2
13578,Williamstown,96 Verdon St,0,0,1,1,h,2500000.0,PI,Sweeney,...,29.427878,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,3
13579,Yarraville,6 Agnes St,0,0,1,1,h,1285000.0,SP,Village,...,19.026298,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,3

In [132]:
# Create the 'Copy' column and set its values to be the same as 'Distance'
df['Distance_copy'] = df['Distance']
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_LabelEncoded,Rooms_OrdinalEncoded,Distance_copy
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,1,2.5
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,1,2.5
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,2,2.5
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,2,2.5
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,3,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,3,16.7
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,2,6.8
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,2,6.8
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,3,6.8
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,3,6.3

In [133]:
# normalization is a process to make values in 0 and 1 range so its effective for data interpretation
# Example: Normalize the 'BP_Normal' column
df['Distance_copy'] = (df['Distance_copy'] - df['Distance_copy'].min()) / (df['Distance_copy'].max() - df['Distance_copy'].min())
# Display the DataFrame with the normalized 'BP_Normal' column
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_LabelEncoded,Rooms_OrdinalEncoded,Distance_copy
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,1,0.051975
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,1,0.051975
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,2,0.051975
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,2,0.051975
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,3,0.051975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,3,0.347193
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,2,0.141372
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,2,0.141372
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,3,0.141372
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,3,0.130977

In [134]:
# Drop the 'Distance_copy' column with inplace
#axis =1 column    0 is row

df.drop(['Distance_copy'], axis=1, inplace=True)
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Rooms_LabelEncoded,Rooms_OrdinalEncoded
0,Abbotsford,85 Turner St,2BHK,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,14.212670,151.96765,1964,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,2,1
1,Abbotsford,25 Bloomburg St,2BHK,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,12.489996,79.00000,1900,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,2,1
2,Abbotsford,5 Charles St,3BHK,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,11.575837,150.00000,1900,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,3,2
3,Abbotsford,40 Federation La,3BHK,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,9.695360,151.96765,1964,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,3,2
4,Abbotsford,55a Park St,4BHK,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,10.954451,142.00000,2014,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4BHK,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,25.534291,151.96765,1981,Maribyrnong,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,4,3
13576,Williamstown,77 Merrett Dr,3BHK,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,18.248288,133.00000,1995,Maribyrnong,-37.85927,144.87904,Western Metropolitan,6380.0,3,2
13577,Williamstown,83 Power St,3BHK,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,20.880613,151.96765,1997,Maribyrnong,-37.85274,144.88738,Western Metropolitan,6380.0,3,2
13578,Williamstown,96 Verdon St,4BHK,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,29.427878,157.00000,1920,Maribyrnong,-37.85908,144.89299,Western Metropolitan,6380.0,4,3
13579,Yarraville,6 Agnes St,4BHK,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,19.026298,112.00000,1920,Maribyrnong,-37.81188,144.88449,Western Metropolitan,6543.0,4,3